name: Publish to SPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

permissions:
    id-token: write
    contents: read

jobs:
  update-sdk:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure version input is provided
      run: |
        if [ -z "${{ github.event.inputs.version }}" ]; then
          echo "Error: Version number is required."
          exit 1
        fi

    - name: Download SDK zip
      run: |
        VERSION=${{ github.event.inputs.version }}
        URL="https://libraries.osano.com/ios/OsanoConsentManagerSDK/OsanoConsentManagerSDK-${VERSION}.zip"
        curl -L $URL -o OsanoConsentManagerSDK-${VERSION}.zip

    - name: Compute checksum
      run: |
        CHECKSUM=$(swift package compute-checksum OsanoConsentManagerSDK-${VERSION}.zip)
        echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV
        rm OsanoConsentManagerSDK-${VERSION}.zip

    - name: Create new version folder
      run: |
        VERSION=${{ github.event.inputs.version }}
        mkdir -p OsanoConsentManagerSDK/${VERSION}
      working-directory: ${{ github.workspace }}

    - name: Copy template.podspec and update attributes
      run: |
        cp template.podspec OsanoConsentManagerSDK/${VERSION}/OsanoConsentManagerSDK.podspec
        VERSION=${{ github.event.inputs.version }}
        URL="https://libraries.osano.com/ios/OsanoConsentManagerSDK/OsanoConsentManagerSDK-${VERSION}.zip"
        sed -i '' "s|s.version      = '<version>'|s.version      = '${VERSION}'|" OsanoConsentManagerSDK/${VERSION}/OsanoConsentManagerSDK.podspec
        sed -i '' "s|s.source       = { :http => '<path-to-s3-zip>' }|s.source       = { :http => '${URL}' }|" OsanoConsentManagerSDK/${VERSION}/OsanoConsentManagerSDK.podspec
      working-directory: ${{ github.workspace }}

    - name: Update Package.swift
      run: |
        VERSION=${{ github.event.inputs.version }}
        CHECKSUM=${{ env.CHECKSUM }}
        sed -i '' "s|url: .*|url: \"https://libraries.osano.com/ios/OsanoConsentManagerSDK/OsanoConsentManagerSDK-${VERSION}.zip\",|" Package.swift
        sed -i '' "s|checksum: .*|checksum: \"${CHECKSUM}\"|" Package.swift
      working-directory: ${{ github.workspace }}

    - name: Install GitHub CLI
      run: |
        brew install gh

    - name: Create branch and commit changes
      run: |
        VERSION=${{ github.event.inputs.version }}
        BRANCH_NAME="update-osano-sdk-${VERSION}"
        git config --global user.name 'Osano Automation'
        git config --global user.email 'automation@osano.com'
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m "Update OsanoConsentManagerSDK to version $VERSION"
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      run: |
        VERSION=${{ github.event.inputs.version }}
        BRANCH_NAME="update-osano-sdk-${VERSION}"
        gh pr create --title "Update OsanoConsentManagerSDK to version $VERSION" --body "This PR updates the OsanoConsentManagerSDK to version $VERSION." --head $BRANCH_NAME --base main
      env:
        GITHUB_TOKEN: ${{ secrets.OSANO_GITHUB_ACCESS_TOKEN }}